version: "3.8"

services:
  db:
    image: postgres
    container_name: disku_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - dis-network
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container 
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@private.org
      PGADMIN_DEFAULT_PASSWORD: admin
    user: "${UID}:${GID}"
    networks:
      - dis-network
    volumes:
      - ./data/pg-admin:/var/lib/pgadmin
    profiles:
      - debug

  frontend:
    build: 
      context: ./frontend

    restart: always
    ports:
      - "5000:5000"
    networks:
      - dis-network
    depends_on:
      - server

  server:
    build: ./backend/db-manager
    restart: always
    container_name: dbmanager
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data

    networks:
      - dis-network
    depends_on:
      scraper:
        condition: service_completed_successfully
      db:
        condition: service_started

  scraper:
    build: ./backend/courses
    restart: on-failure
    volumes:
      - ./data:/data

networks:
  dis-network:
