version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend

    restart: always
    ports:
      - "5000:5000"
    networks:
      - dis-network
    depends_on:
      - server

  server:
    build: ./backend/db-manager
    restart: always
    container_name: dbmanager
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data

    networks:
      - dis-network
    depends_on:
      rust_builder:
        condition: service_completed_successfully


  rust_builder:
    build: ./backend/rust_parser
    image: rust_parser
networks:
  dis-network:
